-- Published studio systems, addressed by a short id.
--
-- Why this table exists: a shared system used to travel inside its own URL
-- fragment, compressed. That worked, needed no server, and produced a
-- two-thousand-character link that nobody can paste into WhatsApp. The document
-- has to live somewhere for the link to be short.
--
-- Design notes:
--
--  · `id` IS THE PUBLIC URL. /s/k7f3q9 . It is a random 7-character Crockford
--    base32 string generated by the function, not a sequence, because a
--    sequential id would let anyone walk every system every coach has ever
--    published. The CHECK pins the alphabet: no i, l, o or u, so nothing a
--    coach reads down the phone is ambiguous.
--
--  · `doc` is the whole System document, the same JSON the editor keeps in
--    localStorage. One jsonb column rather than a normalised set of tables for
--    the same reason the editor does it: it is always read and written whole,
--    versioned as a unit, and its shape is owned by src/studio/schema.ts.
--
--  · A share is UPDATED IN PLACE, keyed by the id the editor remembers
--    (`System.shareId`). Sharing the same system twice does not make a second
--    link — it refreshes the one the coach has already sent, which is the
--    behaviour they expect and the one the old fragment link could never have.
--
--  · NO RLS POLICIES, ON PURPOSE. RLS is on and nothing is granted, so anon and
--    authenticated cannot see this table at all. The only reader and writer is
--    netlify/functions/share.mts, which holds the service-role key and bypasses
--    RLS. That keeps the browser holding no key at all, matching 001.
--
--    When accounts land, this gains `owner uuid references auth.users` and a
--    policy so a coach can list and unpublish their own shares. Until there is
--    an owner to compare against, a policy would be theatre.

create table if not exists public.studio_shares (
  id         text        primary key,
  doc        jsonb       not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint studio_shares_id_shape check (id ~ '^[0-9a-hjkmnp-tv-z]{6,16}$')
);

-- Housekeeping and "what has been published lately", both by recency.
create index if not exists studio_shares_updated_at_idx
  on public.studio_shares (updated_at desc);

alter table public.studio_shares enable row level security;

-- Belt and braces, exactly as in 001: this project does not hand out Supabase's
-- default privileges on public, and this states the intention rather than
-- relying on that staying true.
revoke all on public.studio_shares from anon;
revoke all on public.studio_shares from authenticated;
